### ISSUE TITLE
[Feature]: Bug reporting tool

### ISSUE THREAD

**Issue by logangamesdaily** [IzK-ArcOS/ArcOS-Frontend#40]
### Describe the new feature

Bug reporting app in ArcOS with log uploading, screenshot uploading, etc. with portal for people to view submitted issues
(github issues & feature requests with logs from user embedded in arcos)

### Describe why the feature is useful

Pinpoint exactly where something went wrong

**Comment by IzKuipers** [comment]
Current progress: the Bug Reports settings page has been added to the Settings App as of today:
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/7fd7fc00-e31e-4d20-a531-b85301c8073c)
> **Note**: This is still unrefined and in active development, the screenshot does not represent the end result.

**Comment by logangamesdaily** [comment]
I think this could do with some UI work, and make Admins able to view the bug reports

**Comment by IzKuipers** [comment]
We've migated to a dedicated app, the settings page has been removed. The figma design currently goes as follows: 

![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/7517cad9-0d73-4023-8be8-076226002d32)

This has been communicated with DT and implementation has started approximately 10 minutes ago

**Comment by eversiege** [comment]
What is the progress of Bug Reporter?

**Comment by IzKuipers** [comment]
Closing this issue since the application has been fully implemented:
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/dc75bf7e-9f02-4a6a-9342-7e606db2d878)
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/0f2e49d0-dcf5-42ae-a816-d3c837448d5a)
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/b899e6a6-fe41-4262-8b42-5159c7f0ac0d)
