### ISSUE TITLE
[Bug]: ArcOS Mode:Browser string in settnigs

### ISSUE THREAD

**Issue by sawrams** [IzK-ArcOS/ArcOS-Frontend#47]
### What happened?

I use Desktop version of ArcOS and when i was checking some settings i noticed that it says Browser under "ArcOS Mode", but im using an app, not browser
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/66771772/2826b112-f9b8-4bec-a970-2c3af601c6d9)

### Edition

Desktop (Specfiy version below)

### ArcOS Version

v5.0.9

### Contact Detail(s)

@sawrams at discord

**Comment by IzKuipers** [comment]
![image](https://github.com/IzK-ArcOS/ArcOS-Frontend/assets/76709090/3293ebe4-c38b-4479-8bc2-2802cb512774)
I can confirm that this issue is local to the Settings App's about page as the rest of the OS indicates that it is in the desktop app

**Comment by IzKuipers** [comment]
Confusingly the Settings App shows the correct mode on the Debian package, but this issue was created on the Windows version of the desktop app, so it's possible that [IzK-ArcOS/ArcOS-Electron-Compiler](https://github.com/IzK-ArcOS/ArcOS-Electron-Compiler) didn't include the necessary `/desktop` file used for Desktop app detection.

I'll spin up a development environment on my server to further debug this problem.

**Comment by IzKuipers** [comment]
Resolved, effective in 5.0.10
