### ISSUE TITLE
[Feature]: Customisable cursors and hex for accent colours

### ISSUE THREAD

**Issue by r1sk01** [IzK-ArcOS/ArcOS-Frontend#72]
### Describe the new feature

Adds fully customisable cursors and a colour wheel with hex/rgba for accent colours

### Describe why the feature is useful

It's not useful, it's for aesthetics since some might want different cursors or accent colours which are different from the ones that are available.

**Comment by IzKuipers** [comment]
Custom accent colors are already supported though not in the UI, that'll be implmented in the short term queue. As per the cursors, that's more difficult due to licensing of other cursors. The only custom cursors we currently have have been licensed for use in the project, acquiring other licenses for other cursors can take some time, therefor those will be on the long-term queue for the time being.

**Comment by r1sk01** [comment]
> Custom accent colors are already supported though not in the UI, that'll be implmented in the short term queue. As per the cursors, that's more difficult due to licensing of other cursors. The only custom cursors we currently have have been licensed for use in the project, acquiring other licenses for other cursors can take some time, therefor those will be on the long-term queue for the time being.

Concerning the cursors, I'm talking about users uploading their own cursor packs, although it may be better to upload the cursor pack to ArcFS then be able to use them in ArcOS.

**Comment by Blockyheadman** [comment]
Maybe a selector for each cursor by uploading a file or packs as well.

**Comment by IzKuipers** [comment]
The custom accent color selector is already implemented, the custom cursor option is moved to long term, when and if it'll be implemented is still unknown.
