### ISSUE TITLE
ArcTerm mode can login to nonexistent users.

### ISSUE THREAD

**Issue by logangamesdaily** [IzK-ArcOS/ArcOS-Frontend#81]
### What happened?

Open FTS, click ArcTerm, enter any user that is not on the API then just any password, and for some reason it lets you in. 

### Edition

Website

### Other Browser(s)

Chrome iOS (Latest)

### Contact Detail(s)

it’s a me

**Comment by Blockyheadman** [comment]
@IzKuipers @An-Unnamed-Developer I can confirm this issue is valid and is doable on any system.

**Comment by IzKuipers** [comment]
@Blockyheadman Can you walk me through what exactly you do

**Comment by Blockyheadman** [comment]
> @Blockyheadman Can you walk me through what exactly you do

alright. get a new private window open. fts screen, select arcterm mode. choose community api (for simplicity). enter literally anything for user and password. login as undefined

**Comment by IzKuipers** [comment]
Couple notes:
1. Yes, this issue is a thing unfortunately;
2. FTS or Alt+A (on boot) makes no difference, both still allow you to get in;
3. This only works on accounts that don't exist at all (so entering a valid user but incorrect password is handled correctly)

To fix it:
Check the returns in the `authPrompt` function to ensure its correctly handling the faulty username

**Comment by IzKuipers** [comment]
This bug has been resolved in commits https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/17298285a1ed7b4609d9f89ac63df712320f35e5 and https://github.com/IzK-ArcOS/ArcOS-Frontend/commit/de9d96c74eb22f119f99740899d8aec49f1c4688
